using System;
using GSoft.Dynamite.Globalization.Variations;
using Microsoft.SharePoint.Publishing;

namespace GSoft.Dynamite.Navigation
{
    /// <summary>
    /// Catalog navigation interface.
    /// </summary>
    public interface IVariationNavigationHelper
    {
        /// <summary>
        /// Get the peer url for a SharePoint page
        /// </summary>
        /// <param name="currentUrl">The current page url</param>
        /// <param name="label">The target label to resolve</param>
        /// <returns>The url of the peer page</returns>
        Uri GetPeerPageUrl(Uri currentUrl, VariationLabelInfo label);

        /// <summary>
        /// Get the peer url for a taxonomy navigation page (generated by a term set)
        /// </summary>
        /// <param name="currentUrl">The current page url</param>
        /// <param name="label">The target label to resolve</param>
        /// <returns>The url of the peer page</returns>
        Uri GetPeerCatalogCategoryUrl(Uri currentUrl, VariationLabelInfo label);

        /// <summary>
        /// Get the peer url for a page represents a cross site publishing catalog item 
        /// </summary>
        /// <param name="currentUrl">The current page url</param>
        /// <param name="label">The target label to resolve</param>
        /// <param name="associationKeyManagedPropertyName">The content association key search managed property name</param>
        /// <param name="associationKeyValue">The value of the content association key for the current item</param>
        /// <param name="languageManagedPropertyName">The language search managed property name</param>
        /// <param name="catalogNavigationTermManagedPropertyName">The navigation search managed property name used for the friendly url generation</param>
        /// <returns>The url of the peer page</returns>
        Uri GetPeerCatalogItemUrl(
            Uri currentUrl,
            VariationLabelInfo label,
            string associationKeyManagedPropertyName,
            string associationKeyValue,
            string languageManagedPropertyName,
            string catalogNavigationTermManagedPropertyName);

        /// <summary>
        /// Determine the current navigation context type
        /// </summary>
        /// <returns>The current variation navigation context</returns>
        VariationNavigationType GetCurrentNavigationContextType();

        /// <summary>
        /// Determines whether [is current item] [the specified item URL].
        /// </summary>
        /// <param name="itemUrl">The item URL.</param>
        /// <returns>True if URL is the current catalog item.</returns>
        bool IsCurrentItem(Uri itemUrl);
    }
}
