#
# Module 'Dynamite.PowerShell.Toolkit'
# Generated by: GSoft, Team Dynamite.
# Generated on: 10/24/2013
# > GSoft & Dynamite : http://www.gsoft.com
# > Dynamite Github : https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit
# > Documentation : https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit/wiki
#

<#
	.SYNOPSIS
		Commandlet to add sample items to a SharePoint library

	.DESCRIPTION
		Add sample items in a SharePoint library based on a XML configuration file

    --------------------------------------------------------------------------------------
    Module 'Dynamite.PowerShell.Toolkit'
    by: GSoft, Team Dynamite.
    > GSoft & Dynamite : http://www.gsoft.com
    > Dynamite Github : https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit
    > Documentation : https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit/wiki
    --------------------------------------------------------------------------------------
   
    .NOTES
         Here is the Structure XML schema.

        <Configuration>
	        <Web Url="http:/mysite/sites/mysubsite">
		        <List WebRelativeUrl="/Lists/MyList">
                    <!-- 
                        ID: ID of the content type for newly created items. Must exists in the list.
                        NumberOfItems: If overwrite parameter is not specified, number of items to generate. Ignored otherwise.
                    -->
			        <ContentType ID="0x01008093F9E3678D3D4392C57B0E6929DE05010101" NumberOfItems="20">
                        <!-- 
                            SampleFolder: Path of the folder that contains data for the current field type
                            
                            For TextFields, there is one file by column internal name

                            Column Internal Name: Title >> File Name: Title.txt

                            In the file, separate each string by a new line

                        -->
				        <TextFields SampleFolder="D:\FR\TextFields">
					        <Field InternalName="Title"/>
					        <Field InternalName="Summary"/>
				        </TextFields>
                        <!-- 
                            SampleFolder: Path of the folder that contains data for the current field type
                            
                            For ImageFields, put here your images
                        -->
				        <ImageFields SampleFolder="D:\FR\ImageFields">
					        <Field InternalName="PublishingPageImage"/>
				        </ImageFields>
                        <!-- 
                            SampleFolder: Path of the folder that contains data for the current field type
                            
                            For TaxonomyFields, there is one file by Term Set name

                            Term Set Name: MyTermSet >> File Name: MyTermSet.txt

                            In the file, separate each term by a new line
                        -->
				        <TaxonomyFields SampleFolder="D:\FR\TaxonomyFields" >
					        <Field InternalName="MyTaxonomyField" AssociatedTermSetGroup="MyGroup" AssociatedTermSet="MyTermSetName"/>
				        </TaxonomyFields>
                                                <!-- 
                            SampleFolder: Path of the folder that contains data for the current field type
                            
                            For HTMLFields, there is one file by content sample

                            Article1.txt
                            Article2.txt
                            etc...

                            In the file, you can copy directly the HTML code for the content
                        -->
				        <HTMLFields SampleFolder="D:\FR\HTMLFields">
					        <Field InternalName="PublishingPageContent"/>
				        </HTMLFields>	

				        <UserFields SampleFolder="D:\FR\UserFields">
					        <Field InternalName="Owner"/>
				        </UserFields>		

			        </ContentType>
		        </List>
	        </Web>
        </Configuration>


	.PARAMETER  XmlPath (Mandatory)
		Physical path of the XML configuration file.
		
	.PARAMETER  Overwrite (Optionnal)
		If true, overwrite field values of existing items in the library. Otherwise, create new items.

	.PARAMETER  SyncVariations (Optionnal)
		If true, synchronize items with all variation branches.

	.PARAMETER  ImagesUploadWebUrl (Optionnal)
		If set, specifies the web that contains the images library. If not set, images will be uploaded in the default "Images" library on site collection the root web of the current proceded web.

	.PARAMETER  ImagesUploadLibraryName (Optionnal)
		If set, specifies the image library display name used to uplaod sample images.


	.EXAMPLE
		PS C:\> Add-DSPSampleContent "D:\Data.xml" -Overwrite
        PS C:\> Add-DSPSampleContent "D:\Data.xml" -ImagesUploadWebUrl "http://mydoccenter/" -ImagesUploadLibraryName "Images"

	.OUTPUTS
		n/a. 
    
  .LINK
    GSoft, Team Dynamite on Github
    > https://github.com/GSoft-SharePoint
    
    Dynamite PowerShell Toolkit on Github
    > https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit
    
    Documentation
    > https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit/wiki
    
#>
function Add-DSPSampleContent
{
	[CmdletBinding(DefaultParametersetName="Default")] 
	param
	(
		[Parameter(ParameterSetName="Default", Mandatory=$true, Position=0)]
		[string]$XmlPath,

        [Parameter(ParameterSetName="Default",Mandatory=$false, Position=1)]
		[bool]$Overwrite=$false,

        [Parameter(ParameterSetName="Default",Mandatory=$false, Position=2)]
		[bool]$SyncVariations=$false,

        [Parameter(ParameterSetName="Default",Mandatory=$false, Position=3)]
	    [string]$ImagesUploadWebUrl,

        [Parameter(ParameterSetName="Default",Mandatory=$false, Position=4)]
	    [string]$ImagesUploadLibraryName
	)
	
	$Config = [xml](Get-Content $XmlPath)
	
    if(($ImagesUploadWebUrl -ne $null) -and ($ImagesUploadLibraryName -ne $null))
    {
        Set-Variable -Name "UploadWeb" -Value $ImagesUploadWebUrl -Scope script
        Set-Variable -Name "UploadLibraryName" -Value $ImagesUploadLibraryName -Scope script
        Set-Variable -Name "CustomImageLibrary" -value $true -Scope script
    }

    # Process all Term Groups
	$Config.Configuration.Web | ForEach-Object {
	
		$web = Get-SPWeb -Identity $_.Url
		$webServerRelativeUrl = $web.ServerRelativeUrl
       
        $_.List | ForEach-Object {

            $listUrl = $webServerRelativeUrl + $_.WebRelativeUrl
            $list = $web.GetList($listUrl)

            Add-ListContent $list $_ $Overwrite $SyncVariations
        }   

        if($SyncVariations)
        {
            Start-ListItemPropagation $web.Site.WebApplication
        }
	}
}

function Add-ListContent
{
    param
	(
		[Parameter(Mandatory=$true, Position=0)]
		$SPList,

        [Parameter(Mandatory=$true, Position=1)]
		$ListConfig,

        [Parameter(Mandatory=$true, Position=2)]
		$Overwrite,

        [Parameter(Mandatory=$false, Position=3)]
		$SyncVariations  
	)

        $ListConfig.ContentType | ForEach-Object {

        $contentType = $_
        $folders = @{"TextFields" = $_.TextFields.SampleFolder ; "URLFields" = $_.URLFields.SampleFolder; "ImageFields" = $_.ImageFields.SampleFolder ; "TaxonomyFields" = $_.TaxonomyFields.SampleFolder ; "HTMLFields" = $_.HTMLFields.SampleFolder; "UserFields" = $_.UserFields.SampleFolder }

        # If overwrite, replace all list items content for the content type
        if($Overwrite)
        {
            $spQuery = New-Object Microsoft.SharePoint.SPQuery 
            $camlQuery = "<Where>
                            <BeginsWith>
                                <FieldRef Name='ContentTypeId'/>
                                <Value Type='ContentTypeId'>" + $_.ID + "</Value>
                            </BeginsWith>
                        </Where>
                        <OrderBy>
                            <FieldRef Name='ID' />
                        </OrderBy>" 
            $spQuery.Query = $camlQuery 
            $SPList.GetItems($spQuery) | ForEach-Object {
            
                Process-Fields $_ $folders $contentType

                if($SyncVariations)
                {
                    Sync-DSPItem $_
                }  
            }
        }
        else
        {
            $numberOfItems = $_.NumberOfItems
       
            for ($i=1; $i -le $numberOfItems; $i++)
            {
                $listItem = $SPList.Items.Add()
                $listItem["ContentTypeId"] = $_.ID

                Process-Fields $listItem  $folders $contentType
                
                if($SyncVariations)
                {
                    Sync-DSPItem $listItem
                }           
            }
	   }
    }   
}

function Process-Fields
{
    param
	(
		[Parameter(Mandatory=$true, Position=0)]
		$SPListItem,

        [Parameter(Mandatory=$true, Position=1)]
		$Folders,

        [Parameter(Mandatory=$true, Position=2)]
		$ContentType
	)

    # Text Fields
    if($ContentType.TextFields -ne $null)
    {
        $ContentType.TextFields.Field | ForEach-Object {
			Foreach ($textFieldFolder in $folders["TextFields"]) {	                    
            	Process-TextField $SPListItem $textFieldFolder $_ 
			}
        }
    }

    # Image Fields
    if($ContentType.ImageFields -ne $null)
    {
        $ContentType.ImageFields.Field | ForEach-Object {
            Foreach ($imageFieldFolder in $folders["ImageFields"]) {	        
            	Process-ImageField $SPListItem $imageFieldFolder $_
			}
        }  
    }

    # Taxonomy Fields
    if($ContentType.TaxonomyFields -ne $null)
    {
        $ContentType.TaxonomyFields.Field | ForEach-Object {
        	Foreach ($taxonomyFieldFolder in $folders["TaxonomyFields"]) {       
            	Process-TaxonomyField $SPListItem $taxonomyFieldFolder $_  $_.AssociatedTermSet $_.AssociatedTermSetGroup
			}
        }  
    }

    # HTML Fields
    if($ContentType.HTMLFields -ne $null)
    {
        $ContentType.HTMLFields.Field | ForEach-Object {
        	Foreach ($htmlFieldFolder in $folders["HTMLFields"]) {        
            	Process-HTMLField $SPListItem $htmlFieldFolder $_
			}
        }  
    }
	
	# URL Fields
    if($ContentType.URLFields -ne $null)
    {
        $ContentType.URLFields.Field | ForEach-Object {
            Foreach ($urlFieldFolder in $folders["URLFields"]) {	        
            	Process-TextField $SPListItem $urlFieldFolder $_ 
			}
        }  
    }

    # Boolean Fields
    if($ContentType.BooleanFields -ne $null)
    {
        $ContentType.BooleanFields.Field | ForEach-Object {
                    
            Process-BooleanField $SPListItem $_  
        }  
    }
	
	# Number Fields
    if($ContentType.NumberFields -ne $null)
    {
        $ContentType.NumberFields.Field | ForEach-Object {
                    
            Process-NumberField $SPListItem $_  
        }  
    }
	
	# DateTime Fields
    if($ContentType.DateTimeFields -ne $null)
    {
        $ContentType.DateTimeFields.Field | ForEach-Object {
                    
            Process-DateTimeField $SPListItem $_  
        }  
    }

    # User Fields
    if($ContentType.UserFields -ne $null)
    {
        $ContentType.UserFields.Field | ForEach-Object {
            Foreach ($userFieldFolder in $folders["UserFields"]) {        
            	Process-UserField $SPListItem $userFieldFolder $_  
			}
        }  
    }

    # Approve all items
    $SPListItem["_ModerationStatus"] = 0
    $SPListItem.Update()  
}
  
function Process-ImageField
{
    param
	(
        [Parameter(Mandatory=$true, Position=0)]
		[Microsoft.SharePoint.SPListItem]$SPListItem,

		[Parameter(Mandatory=$true, Position=1)]
		$FolderPath,

        [Parameter(Mandatory=$true, Position=2)]
		$Field
	)

    $isCustomLib = Get-Variable -Name "CustomImageLibrary" -Scope script

    if($isCustomLib)
    {
        $webUrl = (Get-Variable -Name "UploadWeb" -Scope script).Value
        $docLibName = (Get-Variable -Name "UploadLibraryName" -Scope script).Value
    }
    else
    {
        # Default Images Library of the Root Site Collection Web
        $webUrl = $SPListItem.ParentList.ParentWeb.Site.RootWeb.Url
        $docLibName = "Images" 
    }

    if(((Get-ChildItem $FolderPath).Count -gt 0))
    {     
        # Get a random image in the folder
        $imageFilePath = Get-ChildItem $FolderPath | Get-Random -Count 1
           
        # Upload the image in a SharePoint Library
        $imagePath = Add-DSPFile $webUrl $docLibName $imageFilePath.FullName $true
        $image = New-Object Microsoft.SharePoint.Publishing.Fields.ImageFieldValue
        $image.ImageUrl = [Microsoft.SharePoint.Utilities.SPUtility]::ConcatUrls($webUrl, $imagePath)
     
        [Microsoft.SharePoint.Publishing.Fields.ImageFieldValue]$SPListItem[$Field.InternalName] = $image
    }
}

function Process-TextField
{
    param
	(
        [Parameter(Mandatory=$true, Position=0)]
		[Microsoft.SharePoint.SPListItem]$SPListItem,

		[Parameter(Mandatory=$true, Position=1)]
		$FolderPath,

        [Parameter(Mandatory=$true, Position=2)]
		$Field
	)

    if(((Get-ChildItem $FolderPath).Count -gt 0))
    {  
        $textFieldFile = Get-FieldAssociatedFile $FolderPath $Field.InternalName
 
        $fieldName = [System.IO.Path]::GetFileNameWithoutExtension($textFieldFile)

        # Get a random string value
        $randomText = Get-Content $textFieldFile.FullName | Get-Random -Count 1

        $SPListItem[$fieldName] = "$($randomText)"
    }
}

function Process-TaxonomyField
{
    param
	(
        [Parameter(Mandatory=$true, Position=0)]
		[Microsoft.SharePoint.SPListItem]$SPListItem,

		[Parameter(Mandatory=$true, Position=1)]
		$FolderPath,

        [Parameter(Mandatory=$true, Position=2)]
		$Field,

        [Parameter(Mandatory=$true, Position=3)]
		$TermSetName,

        [Parameter(Mandatory=$true, Position=4)]
		$TermSetGroup
	)

    if(((Get-ChildItem $FolderPath).Count -gt 0))
    {  
        $taxonomyFile = Get-FieldAssociatedFile $FolderPath $TermSetName

        # Get a random taxonomy value
        $termSetValue = [System.IO.Path]::GetFileNameWithoutExtension($taxonomyFile)

        # Get a random label for the term set
        $randomTerm = Get-Content $taxonomyFile.FullName | Get-Random -Count 1

        # Get the associated term set
        $termSet = Get-DSPTermSet -GroupName $TermSetGroup -TermSetName $termSetValue
        $term = $termSet.GetTerms($randomTerm, $false)

        # Format field
        $labelGuidPair = [Microsoft.SharePoint.Taxonomy.TaxonomyItem]::NormalizeName($term[0].Labels[0].Value) + [Microsoft.SharePoint.Taxonomy.TaxonomyField]::TaxonomyGuidLabelDelimiter  + $term[0].Id.ToString()

        Set-DSPTaxonomyFieldValue $SPListItem $Field.InternalName $labelGuidPair
    }
}

function Process-HTMLField
{
    param
	(
        [Parameter(Mandatory=$true, Position=0)]
		[Microsoft.SharePoint.SPListItem]$SPListItem,

		[Parameter(Mandatory=$true, Position=1)]
		$FolderPath,

        [Parameter(Mandatory=$true, Position=2)]
		$Field
	)
   
    if(((Get-ChildItem $FolderPath).Count -gt 0))
    {  
        # Get a random content
        $articleText = Get-ChildItem $FolderPath | Get-Random -Count 1 | Get-Content | out-string

        $SPListItem[$Field.InternalName] = $articleText
    }
}

function Process-BooleanField
{
    param
	(
        [Parameter(Mandatory=$true, Position=0)]
		[Microsoft.SharePoint.SPListItem]$SPListItem,

        [Parameter(Mandatory=$true, Position=1)]
		$Field
	)
   
	# Get a random content
	$booleanValue = Get-Random "True","False" -Count 1
    
	$SPListItem[$Field.InternalName] = [System.Convert]::ToBoolean($booleanValue)   
}

function Process-NumberField
{
    param
	(
        [Parameter(Mandatory=$true, Position=0)]
		[Microsoft.SharePoint.SPListItem]$SPListItem,

        [Parameter(Mandatory=$true, Position=1)]
		$Field
	)
   
	# Get a random content
	$numberValue = Get-Random -Minimum 0 -Maximum 10
    
	$SPListItem[$Field.InternalName] = [System.Convert]::ToInt32($numberValue)   
}
$global:abc = ""
function Process-DateTimeField
{
    param
	(
        [Parameter(Mandatory=$true, Position=0)]
		[Microsoft.SharePoint.SPListItem]$SPListItem,

        [Parameter(Mandatory=$true, Position=1)]
		$Field
	)
    
	$SPListItem[$Field.InternalName] = $Field.DateTime
}

function Process-UserField
{
    param
	(
        [Parameter(Mandatory=$true, Position=0)]
		[Microsoft.SharePoint.SPListItem]$SPListItem,

		[Parameter(Mandatory=$true, Position=1)]
		$FolderPath,

        [Parameter(Mandatory=$true, Position=2)]
		$Field
	)

    if(((Get-ChildItem $FolderPath).Count -gt 0))
    {  
        $textFieldFile = Get-FieldAssociatedFile $FolderPath $Field.InternalName
 
        $fieldName = [System.IO.Path]::GetFileNameWithoutExtension($textFieldFile)

        # Get a random string value
        $randomUser = Get-Content $textFieldFile.FullName | Get-Random -Count 1

        # Get the user value
        $web = $SPListItem.parentList.ParentWeb
        $spUser = $web.EnsureUser($randomUser)


        if ($spUser -ne $null)
        {
          $SPListItem[$fieldName] = $spUser  
        }
    }
}

function Get-FieldAssociatedFile
{
    param
	(
		[Parameter(Mandatory=$true, Position=0)]
		$FolderPath,

        [Parameter(Mandatory=$true, Position=1)]
		$FileName
	)

    #Skip .template files
    return Get-ChildItem $FolderPath | Where-Object {$_.BaseName -eq $FileName -and $_.Extension -eq ".txt"}
}

<#
	.SYNOPSIS
		Commandlet to add reusable content snippets

	.DESCRIPTION
		Add reusable content snippets for the site collection

    --------------------------------------------------------------------------------------
    Module 'Dynamite.PowerShell.Toolkit'
    by: GSoft, Team Dynamite.
    > GSoft & Dynamite : http://www.gsoft.com
    > Dynamite Github : https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit
    > Documentation : https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit/wiki
    --------------------------------------------------------------------------------------
   
    .NOTES
         Here is the Structure XML schema.

        <Configuration>
	        <Site Url="http://somewhere">
		        <Snippet Title="Page inexistante (FR)" AutomaticUpdate="True" ShowInRibbon="True" >
			        <Html><![CDATA[<p>Désolé, cette page n'est pas disponible dans en français, vous pouvez accéder à la page originale en cliquant <a id="peerPageUrl">ici</a><p>]]></Html>
		        </Snippet>
	        </Site>
        </Configuration>

	.PARAMETER  XmlPath (Mandatory)
		Physical path of the XML configuration file.

	.PARAMETER  Delete (Optionnal)
		Delete the actual configuration

	.EXAMPLE
		PS C:\> Add-DSPReusableContentSnippets "D:\Data.xml" 
        PS C:\> Add-DSPReusableContentSnippets "D:\Data.xml" -Delete

	.OUTPUTS
		n/a. 
    
  .LINK
    GSoft, Team Dynamite on Github
    > https://github.com/GSoft-SharePoint
    
    Dynamite PowerShell Toolkit on Github
    > https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit
    
    Documentation
    > https://github.com/GSoft-SharePoint/Dynamite-PowerShell-Toolkit/wiki
    
#>
function Add-DSPReusableContentSnippets
{
    [CmdletBinding()] 
	param
	(
		[Parameter(Mandatory=$true, Position=0)]
		[string]$XmlPath,

		[Parameter(Mandatory=$false, Position=1)]
		[switch]$Delete

	)
	
	$Config = [xml](Get-Content $XmlPath -Encoding UTF8)

    $reusableContentListIdPropertyName = "_ReusableContentListId";

    $Config.Configuration.Site | ForEach-Object {
                    
        $site = Get-SPSite $_.Url

        $rootWeb = $site.RootWeb

        # Get the Reusable Content List
        if ($rootWeb.AllProperties.ContainsKey($reusableContentListIdPropertyName))
        {
            [Guid]$reusableContentListId = New-Object System.Guid ($rootWeb.AllProperties[$reusableContentListIdPropertyName].ToString());
            $list = $rootWeb.Lists[$reusableContentListId]

            $_.Snippet | ForEach-Object {

                $title = $_.Title

                $spQuery = New-Object Microsoft.SharePoint.SPQuery
                $camlQuery = '<Where><Eq><FieldRef Name="Title"/><Value Type="Text">'+ $title + '</Value></Eq></Where>'

                $spQuery.Query = $camlQuery
                $spQuery.RowLimit = 1
                $spListItems = $list.GetItems($spQuery)

                if($spListItems.Count -eq 0)
                {            
                    if($Delete -eq $false)
                    {        
                        # Add items
                        $listItem = $list.Items.Add()
                        $listItem["Title"] = $_.Title
                        $listItem["ShowInRibbon"] = [System.Convert]::ToBoolean($_.ShowInRibbon)
                        $listItem["AutomaticUpdate"] = [System.Convert]::ToBoolean($_.AutomaticUpdate)                   
                        $listItem["ReusableHtml"] = $_.Html.InnerText
                        $listItem.Update()
                    }
                    else
                    {
                        Write-Verbose "Reusable Snippet with title '$title' doesn't exists in the list"
                    }
                }
                else
                {
                    Write-Verbose "Reusable Snippet with title '$title' already exists in the list"

                    if($Delete)
                    {
                        Write-Verbose "Deleting Snippet with title '$title'"
                        $list.Items.DeleteItemById($spListItems[0].ID)
                    }
                       
                }
            }
        }
    }    
}