//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSoft.Dynamite.Examples.Parts.ControlTemplates {
    
    
    public partial class ProjectScripts {
        
        /// <summary>
        /// ProjectScriptLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ProjectScriptLink;
        
        /// <summary>
        /// ProjectCustomScriptLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ProjectCustomScriptLink;
    }
}
